import { defineConfig } from 'vite';
import webExtension from 'vite-plugin-web-extension';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig(({ mode }) => {
  const isFirefox = mode === 'firefox';
  const browser = isFirefox ? 'firefox' : 'chrome';
  const outDir = isFirefox ? 'dist/firefox' : 'dist/chrome';

  function buildManifest() {
    const base = JSON.parse(readFileSync(resolve(__dirname, 'manifest.json'), 'utf-8'));
    if (isFirefox) {
      // Firefox MV3 requires background.scripts alongside service_worker.
      // scripts must reference the compiled .js output; service_worker can stay as .ts
      // because the plugin handles the .ts → .js transformation on that field.
      const swSource = base.background.service_worker as string;
      const swOutput = swSource.replace(/\.ts$/, '.js');
      base.background = {
        scripts: [swOutput],
        service_worker: swSource,
        type: 'module',
      };
    } else {
      delete base.browser_specific_settings;
      // Chrome Web Store requires PNG icons; SVG is unsupported for submission.
      // PNGs are generated by scripts/generate-icons.js via the prebuild:chrome hook.
      const pngIcons = {
        '16': 'icons/icon-16.png',
        '32': 'icons/icon-32.png',
        '48': 'icons/icon-48.png',
        '128': 'icons/icon-128.png',
      };
      base.icons = pngIcons;
      base.action.default_icon = pngIcons;
    }
    return base;

  }

  return {
    resolve: {
      alias: { '@': '/src' },
    },
    build: {
      outDir,
      emptyOutDir: true,
      sourcemap: mode === 'development',
      target: 'es2022',
    },
    plugins: [
      webExtension({
        manifest: buildManifest,
        browser,
        additionalInputs: ['src/app/index.html'],
        webExtConfig: {
          startUrl: ['about:newtab'],
        },
      }),
    ],
  };
});
